apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: odainmair/abc-company/client
        env:
        - name: JWT_KEY
          valueFrom:
                secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
  - name: client
    port: 3000
    targetPort: 3000

