name: tests-complaints

on:
  pull_request:
    paths:
      - 'complaints/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd complaints && npm install && npm run test:ci